# [gopkg.in/yaml.v3 v3.0.1] git ls-remote https://github.com/go-yaml/yaml f6f7691b1fdeb513f56608cd2c32c51f8194bf51
SRCREV_yaml.v3 = "f6f7691b1fdeb513f56608cd2c32c51f8194bf51"
SRC_URI += "git://github.com/go-yaml/yaml;name=yaml.v3;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/gopkg.in/yaml.v3"

# [golang.org/x/net v0.47.0] git ls-remote https://go.googlesource.com/net 9a296438e54dff851a45667aa645a97003b44db5
SRCREV_net = "9a296438e54dff851a45667aa645a97003b44db5"
SRC_URI += "git://go.googlesource.com/net;name=net;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/net"

# [golang.org/x/sys v0.38.0] git ls-remote https://go.googlesource.com/sys 15129aafc3056028aa2694528ac20373f8cd34e4
SRCREV_sys = "15129aafc3056028aa2694528ac20373f8cd34e4"
SRC_URI += "git://go.googlesource.com/sys;name=sys;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/sys"

# [golang.org/x/arch v0.8.0] git ls-remote https://go.googlesource.com/arch 5d0b1102bee052ce00bf47f9cfef8f73d2ac6d46
SRCREV_arch = "5d0b1102bee052ce00bf47f9cfef8f73d2ac6d46"
SRC_URI += "git://go.googlesource.com/arch;name=arch;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/arch"

# [golang.org/x/text v0.31.0] git ls-remote https://go.googlesource.com/text e7ff6b3572e1a83c072ef150c985f86603986e1b
SRCREV_text = "e7ff6b3572e1a83c072ef150c985f86603986e1b"
SRC_URI += "git://go.googlesource.com/text;name=text;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/text"

# [golang.org/x/crypto v0.45.0] git ls-remote https://go.googlesource.com/crypto 4e0068c0098be10d7025c99ab7c50ce454c1f0f9
SRCREV_crypto = "4e0068c0098be10d7025c99ab7c50ce454c1f0f9"
SRC_URI += "git://go.googlesource.com/crypto;name=crypto;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/golang.org/x/crypto"

# [github.com/gin-gonic/gin v1.10.0] git ls-remote https://github.com/gin-gonic/gin 75ccf94d605a05fe24817fc2f166f6f2959d5cea
SRCREV_gin = "75ccf94d605a05fe24817fc2f166f6f2959d5cea"
SRC_URI += "git://github.com/gin-gonic/gin;name=gin;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/gin-gonic/gin"

# [github.com/tidwall/gjson v1.18.0] git ls-remote https://github.com/tidwall/gjson 133f42ce2d99d6adb6b5885af6d20939dc4b6fe9
SRCREV_gjson = "133f42ce2d99d6adb6b5885af6d20939dc4b6fe9"
SRC_URI += "git://github.com/tidwall/gjson;name=gjson;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/tidwall/gjson"

# [github.com/tidwall/sjson v1.2.5] git ls-remote https://github.com/tidwall/sjson b279807a1bad9fa155988667d97a3d2fff4061b5
SRCREV_sjson = "b279807a1bad9fa155988667d97a3d2fff4061b5"
SRC_URI += "git://github.com/tidwall/sjson;name=sjson;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/tidwall/sjson"

# [github.com/goccy/go-json v0.10.2] git ls-remote https://github.com/goccy/go-json 8e8cdeacf2f2faef082f32848138f0f9af7cfb66
SRCREV_go-json = "8e8cdeacf2f2faef082f32848138f0f9af7cfb66"
SRC_URI += "git://github.com/goccy/go-json;name=go-json;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/goccy/go-json"

# [github.com/tidwall/match v1.1.1] git ls-remote https://github.com/tidwall/match 4c9fc61b493b7aa0a3d347e9190aa78c5bec09cf
SRCREV_match = "4c9fc61b493b7aa0a3d347e9190aa78c5bec09cf"
SRC_URI += "git://github.com/tidwall/match;name=match;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/tidwall/match"

# [github.com/cloudwego/iasm v0.2.0] git ls-remote https://github.com/cloudwego/iasm db7298c17e362736a9954240db007c2432bf1fa1
SRCREV_iasm = "db7298c17e362736a9954240db007c2432bf1fa1"
SRC_URI += "git://github.com/cloudwego/iasm;name=iasm;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/cloudwego/iasm"

# [github.com/leodido/go-urn v1.4.0] git ls-remote https://github.com/leodido/go-urn d725923fe33ce69c89b9e2033d069099b498224f
SRCREV_go-urn = "d725923fe33ce69c89b9e2033d069099b498224f"
SRC_URI += "git://github.com/leodido/go-urn;name=go-urn;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/leodido/go-urn"

# [github.com/tidwall/pretty v1.2.1] git ls-remote https://github.com/tidwall/pretty 9090695766b652478676cc3e55bc3187056b1ff0
SRCREV_pretty = "9090695766b652478676cc3e55bc3187056b1ff0"
SRC_URI += "git://github.com/tidwall/pretty;name=pretty;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/tidwall/pretty"

# [github.com/bytedance/sonic v1.11.6] git ls-remote https://github.com/bytedance/sonic 2b66aefcd60d189cff2669213f682557216b686f
SRCREV_sonic = "2b66aefcd60d189cff2669213f682557216b686f"
SRC_URI += "git://github.com/bytedance/sonic;name=sonic;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/bytedance/sonic"

# [github.com/davecgh/go-spew v1.1.1] git ls-remote https://github.com/davecgh/go-spew 8991bc29aa16c548c550c7ff78260e27b9ab7c73
SRCREV_go-spew = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
SRC_URI += "git://github.com/davecgh/go-spew;name=go-spew;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/davecgh/go-spew"

# [github.com/gin-contrib/sse v0.1.0] git ls-remote https://github.com/gin-contrib/sse 54d8467d122d380a14768b6b4e5cd7ca4755938f
SRCREV_sse = "54d8467d122d380a14768b6b4e5cd7ca4755938f"
SRC_URI += "git://github.com/gin-contrib/sse;name=sse;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/gin-contrib/sse"

# [github.com/mattn/go-isatty v0.0.20] git ls-remote https://github.com/mattn/go-isatty a7c02353c47bc4ec6b30dc9628154ae4fe760c11
SRCREV_go-isatty = "a7c02353c47bc4ec6b30dc9628154ae4fe760c11"
SRC_URI += "git://github.com/mattn/go-isatty;name=go-isatty;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/mattn/go-isatty"

# [github.com/ugorji/go/codec v1.2.12] git ls-remote https://github.com/ugorji/go 43b79bfcab412eeb73e92181a2190e97a5520566
SRCREV_codec = "43b79bfcab412eeb73e92181a2190e97a5520566"
SRC_URI += "git://github.com/ugorji/go;name=codec;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/ugorji/go/codec"

# [google.golang.org/protobuf v1.34.1] git ls-remote https://github.com/protocolbuffers/protobuf-go 4a76e11653e368b9331815e1eb98e0cedc28997f
SRCREV_protobuf = "4a76e11653e368b9331815e1eb98e0cedc28997f"
SRC_URI += "git://github.com/protocolbuffers/protobuf-go;name=protobuf;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/google.golang.org/protobuf"

# [github.com/stretchr/testify v1.9.0] git ls-remote https://github.com/stretchr/testify bb548d0473d4e1c9b7bbfd6602c7bf12f7a84dd2
SRCREV_testify = "bb548d0473d4e1c9b7bbfd6602c7bf12f7a84dd2"
SRC_URI += "git://github.com/stretchr/testify;name=testify;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/stretchr/testify"

# [github.com/json-iterator/go v1.1.12] git ls-remote https://github.com/json-iterator/go 024077e996b048517130b21ea6bf12aa23055d3d
SRCREV_go = "024077e996b048517130b21ea6bf12aa23055d3d"
SRC_URI += "git://github.com/json-iterator/go;name=go;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/json-iterator/go"

# [github.com/billziss-gh/golib v0.2.0] git ls-remote https://github.com/billziss-gh/golib 96c1ae5b8b676c005d854315cbd73bd72b9b0c65
SRCREV_golib = "96c1ae5b8b676c005d854315cbd73bd72b9b0c65"
SRC_URI += "git://github.com/billziss-gh/golib;name=golib;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/billziss-gh/golib"

# [github.com/fsnotify/fsnotify v1.9.0] git ls-remote https://github.com/fsnotify/fsnotify ae0e7923765f64fb8061396db7edebb558cf6093
SRCREV_fsnotify = "ae0e7923765f64fb8061396db7edebb558cf6093"
SRC_URI += "git://github.com/fsnotify/fsnotify;name=fsnotify;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/fsnotify/fsnotify"

# [github.com/cloudwego/base64x v0.1.4] git ls-remote https://github.com/cloudwego/base64x aa02bf235e2a286ef3a99bacefb460195fc5a16b
SRCREV_base64x = "aa02bf235e2a286ef3a99bacefb460195fc5a16b"
SRC_URI += "git://github.com/cloudwego/base64x;name=base64x;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/cloudwego/base64x"

# [github.com/klauspost/cpuid/v2 v2.2.7] git ls-remote https://github.com/klauspost/cpuid 486f6ae65fec6bbb15e6f6bff15036f7bc50d4c4
SRCREV_v2 = "486f6ae65fec6bbb15e6f6bff15036f7bc50d4c4"
SRC_URI += "git://github.com/klauspost/cpuid;name=v2;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/klauspost/cpuid/v2"

# [github.com/modern-go/reflect2 v1.0.2] git ls-remote https://github.com/modern-go/reflect2 2b33151c9bbc5231aea69b8861c540102b087070
SRCREV_reflect2 = "2b33151c9bbc5231aea69b8861c540102b087070"
SRC_URI += "git://github.com/modern-go/reflect2;name=reflect2;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/modern-go/reflect2"

# [github.com/pmezard/go-difflib v1.0.0] git ls-remote https://github.com/pmezard/go-difflib 792786c7400a136282c1664665ae0a8db921c6c2
SRCREV_go-difflib = "792786c7400a136282c1664665ae0a8db921c6c2"
SRC_URI += "git://github.com/pmezard/go-difflib;name=go-difflib;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/pmezard/go-difflib"

# [github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd] git ls-remote https://github.com/modern-go/concurrent bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94
SRCREV_concurrent = "bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94"
SRC_URI += "git://github.com/modern-go/concurrent;name=concurrent;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/modern-go/concurrent"

# [github.com/pelletier/go-toml/v2 v2.2.2] git ls-remote https://github.com/pelletier/go-toml a3d5a0bb530b5206c728eed9cb57323061922bcb
SRCREV_go-toml-v2 = "a3d5a0bb530b5206c728eed9cb57323061922bcb"
SRC_URI += "git://github.com/pelletier/go-toml;name=go-toml-v2;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/pelletier/go-toml/v2"

# [github.com/go-playground/locales v0.14.1] git ls-remote https://github.com/go-playground/locales ce315c8672599942003599943a1e64288f55b03f
SRCREV_locales = "ce315c8672599942003599943a1e64288f55b03f"
SRC_URI += "git://github.com/go-playground/locales;name=locales;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/go-playground/locales"

# [github.com/bytedance/sonic/loader v0.1.1] git ls-remote https://github.com/bytedance/sonic 51ea135322cab599c287fe6418df4c2e3c32b65e
SRCREV_loader = "51ea135322cab599c287fe6418df4c2e3c32b65e"
SRC_URI += "git://github.com/bytedance/sonic;name=loader;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/bytedance/sonic/loader"

# [github.com/gabriel-vasile/mimetype v1.4.3] git ls-remote https://github.com/gabriel-vasile/mimetype e64d6bdb3607578757d31380818651a9fc95ca8b
SRCREV_mimetype = "e64d6bdb3607578757d31380818651a9fc95ca8b"
SRC_URI += "git://github.com/gabriel-vasile/mimetype;name=mimetype;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/gabriel-vasile/mimetype"

# [github.com/twitchyliquid64/golang-asm v0.15.1] git ls-remote https://github.com/twitchyliquid64/golang-asm 8d7f1f783b11f9a00f5bcdfcae17f5ac8f22512e
SRCREV_golang-asm = "8d7f1f783b11f9a00f5bcdfcae17f5ac8f22512e"
SRC_URI += "git://github.com/twitchyliquid64/golang-asm;name=golang-asm;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/twitchyliquid64/golang-asm"

# [github.com/go-playground/validator/v10 v10.20.0] git ls-remote https://github.com/go-playground/validator e20b94842ab102ba94e73eaf66f5c0466e405882
SRCREV_v10 = "e20b94842ab102ba94e73eaf66f5c0466e405882"
SRC_URI += "git://github.com/go-playground/validator;name=v10;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/go-playground/validator/v10"

# [github.com/go-playground/universal-translator v0.18.1] git ls-remote https://github.com/go-playground/universal-translator f83cd526536e253181a13835b00cd107f627c505
SRCREV_universal-translator = "f83cd526536e253181a13835b00cd107f627c505"
SRC_URI += "git://github.com/go-playground/universal-translator;name=universal-translator;protocol=https;nobranch=1;destsuffix=${GO_SRCURI_DESTSUFFIX}/vendor.fetch/github.com/go-playground/universal-translator"

