#
# Copyright (C) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: GPL-2.0-only
#

DISTRO_FEATURES:append = " llama-cpp"
IMAGE_INSTALL:append = " llama-cpp"

INIT_MANAGER = "systemd"
IMAGE_INSTALL:append = " kernel-modules"
