#
# Copyright (C) 2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: GPL-2.0-only
#

DISTRO_FEATURES_NATIVE:append = " ollama"
DISTRO_FEATURES:append = " ollama"

IMAGE_INSTALL:append = " ollama"

INIT_MANAGER = "systemd"
IMAGE_INSTALL:append = " kernel-modules"
