# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-llm"
BBFILE_PATTERN_meta-llm = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-llm = "5"

LAYERVERSION_meta-llm = "1"

LAYERSERIES_COMPAT_meta-llm = "wrynose"

LAYERDEPENDS_meta-llm = " \
    core \
    meta-python \
"

LAYER_PATH_meta-llm = "${LAYERDIR}"

NON_MULTILIB_RECIPES:append = " ollama llama-cpp"

PREFERRED_RPROVIDER_qwen3.5-common ?= "ol-qwen3.5-0.8b"
PREFERRED_RPROVIDER_gemma3-common ?= "ol-gemma3-1b"

BBFILES_DYNAMIC += " \
    tegra:${LAYERDIR}/dynamic-layers/meta-tegra/recipes*/*/*.bb \
    tegra:${LAYERDIR}/dynamic-layers/meta-tegra/recipes*/*/*.bbappend \
"
